spring.application.name=monFax-backend

# URL de connexion � la base de donn�es

spring.datasource.url=jdbc:postgresql://localhost:5432/monFax_db

# Identifiants de connexion nom et mot de passe postgres

spring.datasource.username=postgres
spring.datasource.password=springpassword

# Driver PostgreSQL

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# configuration pour voir les requ�tes SQL g�n�r�es

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# Configuration JWT
jwt.secret=monSuperSecretJwtKey1234567890123456

# Configuration des ressources
resources.base-dir=C:\temp

# Configuration de PayDunya
paydunya.master-key=F3JRb8Pu-MUhG-QmwQ-5ok7-U6tAmMz9v2sM
paydunya.private-key=test_private_Bgy88xixjBMQ3dDAPbJMYwq02mh
paydunya.token=fJcCAqu2fo7QksIcV7FB
paydunya.url=https://app.paydunya.com/sandbox-api/v1/checkout-invoice/create
paydunya.softpay-url=https://app.paydunya.com/sandbox-api/v1/softpay/checkout/make-payment

server.port= 9000